//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno()
        {
            this.alumno_en_grupo = new HashSet<alumno_en_grupo>();
            this.boletines = new HashSet<boletines>();
            this.comentario_alumno = new HashSet<comentario_alumno>();
            this.clase_express = new HashSet<clase_express>();
            this.pasar_lista = new HashSet<pasar_lista>();
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int idalumno { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string nif { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string telefono_2 { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<bool> autoriza_foto { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> user_active { get; set; }
        public string direccion { get; set; }
        public string cod_postal { get; set; }
        public string provincia { get; set; }
        public string poblacion { get; set; }
        public Nullable<System.DateTime> fecha_naciemiento { get; set; }
        public Nullable<bool> alow_photo { get; set; }
        public byte[] photo { get; set; }
        public Nullable<bool> prueba { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno_en_grupo> alumno_en_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boletines> boletines { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario_alumno> comentario_alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clase_express> clase_express { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pasar_lista> pasar_lista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
