//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno_en_grupo
    {
        public int idalumno_en_grupo { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<System.DateTime> fecha_matricula { get; set; }
        public Nullable<bool> isPrueba { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual grupos grupos { get; set; }
    }
}
