//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int idaudit { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string sql_query { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
