//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class boletines_info
    {
        public int idboletines_alumno { get; set; }
        public Nullable<int> id_boletin { get; set; }
        public Nullable<int> id_skill { get; set; }
        public Nullable<int> id_nota { get; set; }
    
        public virtual boletines boletines { get; set; }
        public virtual notas notas { get; set; }
        public virtual skills skills { get; set; }
    }
}
