//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class clase_express
    {
        public int idclase_express { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<int> idAula { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string dias { get; set; }
        public Nullable<bool> ciclico { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> idnivel_curso { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual aulas aulas { get; set; }
        public virtual nivel_curso nivel_curso { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
        public virtual profesores profesores { get; set; }
    }
}
