//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.alumno = new HashSet<alumno>();
            this.descuento_cliente = new HashSet<descuento_cliente>();
            this.recibo_head = new HashSet<recibo_head>();
        }
    
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string razon_social { get; set; }
        public string nif { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public string direccion { get; set; }
        public string cod_postal { get; set; }
        public string provincia { get; set; }
        public string poblacion { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> is_activo { get; set; }
        public string iban { get; set; }
        public string titular_cuenta { get; set; }
        public Nullable<int> forma_de_pago { get; set; }
        public Nullable<bool> is_oficial { get; set; }
        public Nullable<System.DateTime> f_active_init { get; set; }
        public Nullable<System.DateTime> f_active_end { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno> alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<descuento_cliente> descuento_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibo_head> recibo_head { get; set; }
    }
}
