//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario_grupo
    {
        public int idcomentario_grupo { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<System.DateTime> fecha_clase { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public string comentario { get; set; }
    
        public virtual grupos grupos { get; set; }
        public virtual profesores profesores { get; set; }
    }
}
