//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_horariosEntities : DbContext
    {
        public gestion_horariosEntities()
            : base("name=gestion_horariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public gestion_horariosEntities(bool ciclico) : base("name=gestion_horariosEntities")
        {
            this.Configuration.ProxyCreationEnabled = ciclico;
        }
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<alumno_en_grupo> alumno_en_grupo { get; set; }
        public virtual DbSet<audit> audit { get; set; }
        public virtual DbSet<aulas> aulas { get; set; }
        public virtual DbSet<boletines> boletines { get; set; }
        public virtual DbSet<boletines_info> boletines_info { get; set; }
        public virtual DbSet<centros> centros { get; set; }
        public virtual DbSet<clase_express> clase_express { get; set; }
        public virtual DbSet<clase_grupo> clase_grupo { get; set; }
        public virtual DbSet<clase_impartida> clase_impartida { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<comentario_alumno> comentario_alumno { get; set; }
        public virtual DbSet<comentario_grupo> comentario_grupo { get; set; }
        public virtual DbSet<curso_lectivo> curso_lectivo { get; set; }
        public virtual DbSet<descuento_cliente> descuento_cliente { get; set; }
        public virtual DbSet<evento_grupo> evento_grupo { get; set; }
        public virtual DbSet<generacion_recibos> generacion_recibos { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<libros> libros { get; set; }
        public virtual DbSet<libross_digitales> libross_digitales { get; set; }
        public virtual DbSet<mail_adjunto_en_message> mail_adjunto_en_message { get; set; }
        public virtual DbSet<mail_message> mail_message { get; set; }
        public virtual DbSet<mail_message_adjuntos> mail_message_adjuntos { get; set; }
        public virtual DbSet<mail_message_folder> mail_message_folder { get; set; }
        public virtual DbSet<mail_message_users> mail_message_users { get; set; }
        public virtual DbSet<nivel_curso> nivel_curso { get; set; }
        public virtual DbSet<nomina_head> nomina_head { get; set; }
        public virtual DbSet<nomina_line> nomina_line { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<pasar_lista> pasar_lista { get; set; }
        public virtual DbSet<profesor_en_grupo> profesor_en_grupo { get; set; }
        public virtual DbSet<profesores> profesores { get; set; }
        public virtual DbSet<recibo_head> recibo_head { get; set; }
        public virtual DbSet<recibo_line> recibo_line { get; set; }
        public virtual DbSet<refreshtoken> refreshtoken { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<serie_recibo> serie_recibo { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<tabla_gastos> tabla_gastos { get; set; }
        public virtual DbSet<tipo_producto> tipo_producto { get; set; }
        public virtual DbSet<userclaims> userclaims { get; set; }
        public virtual DbSet<userlogins> userlogins { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<recibos> recibos { get; set; }
    }
}
