//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class descuento_cliente
    {
        public int iddescuento_cliente { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> tipo_descuento { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
