//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public grupos()
        {
            this.alumno_en_grupo = new HashSet<alumno_en_grupo>();
            this.boletines = new HashSet<boletines>();
            this.clase_grupo = new HashSet<clase_grupo>();
            this.clase_impartida = new HashSet<clase_impartida>();
            this.comentario_grupo = new HashSet<comentario_grupo>();
            this.evento_grupo = new HashSet<evento_grupo>();
            this.pasar_lista = new HashSet<pasar_lista>();
            this.profesor_en_grupo = new HashSet<profesor_en_grupo>();
        }
    
        public int idgrupos { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_aula { get; set; }
        public Nullable<int> id_nivel { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
        public string dias { get; set; }
        public Nullable<System.DateTime> hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_fin { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public Nullable<bool> se_repite { get; set; }
        public Nullable<int> id_libro { get; set; }
        public Nullable<bool> id_activo { get; set; }
        public Nullable<int> edadMaxima { get; set; }
        public Nullable<int> edadMinima { get; set; }
        public Nullable<bool> es_facturacion_mensual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alumno_en_grupo> alumno_en_grupo { get; set; }
        public virtual aulas aulas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boletines> boletines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clase_grupo> clase_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clase_impartida> clase_impartida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario_grupo> comentario_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_grupo> evento_grupo { get; set; }
        public virtual libros libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pasar_lista> pasar_lista { get; set; }
        public virtual nivel_curso nivel_curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesor_en_grupo> profesor_en_grupo { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
    }
}
