//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class libross_digitales
    {
        public int id { get; set; }
        public Nullable<int> id_libro { get; set; }
        public Nullable<System.DateTime> fecha_carga { get; set; }
        public Nullable<int> version { get; set; }
        public string mime { get; set; }
        public byte[] blob { get; set; }
    
        public virtual libros libros { get; set; }
    }
}
