//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_message_adjuntos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mail_message_adjuntos()
        {
            this.mail_adjunto_en_message = new HashSet<mail_adjunto_en_message>();
            this.mail_adjunto_en_message1 = new HashSet<mail_adjunto_en_message>();
        }
    
        public int idmail_message_adjuntos { get; set; }
        public string filename { get; set; }
        public string mime_tipe { get; set; }
        public byte[] body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail_adjunto_en_message> mail_adjunto_en_message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail_adjunto_en_message> mail_adjunto_en_message1 { get; set; }
    }
}
