//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mail_message()
        {
            this.mail_message_users = new HashSet<mail_message_users>();
        }
    
        public int idmail_message { get; set; }
        public Nullable<int> id_usuario_emisor { get; set; }
        public string id_usuario_receptor { get; set; }
        public string asunto { get; set; }
        public string cuerpo { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<bool> leido { get; set; }
        public Nullable<bool> id_respondido { get; set; }
        public Nullable<bool> is_html { get; set; }
        public Nullable<int> id_carpeta { get; set; }
    
        public virtual mail_message_folder mail_message_folder { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail_message_users> mail_message_users { get; set; }
    }
}
