//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_adjunto_en_message
    {
        public int idmail_adjunto_en_message { get; set; }
        public Nullable<int> id_message { get; set; }
        public Nullable<int> id_adjunto { get; set; }
    
        public virtual mail_message_adjuntos mail_message_adjuntos { get; set; }
        public virtual mail_message_adjuntos mail_message_adjuntos1 { get; set; }
    }
}
