//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class nomina_line
    {
        public int idnomina_line { get; set; }
        public Nullable<int> id_nom_header { get; set; }
        public Nullable<int> concepto { get; set; }
        public Nullable<decimal> importe { get; set; }
    
        public virtual nomina_head nomina_head { get; set; }
    }
}
