//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo_head
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recibo_head()
        {
            this.recibo_line = new HashSet<recibo_line>();
        }
    
        public int idrecibo_head { get; set; }
        public Nullable<int> id_curso { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> serie { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<System.DateTime> fecha_cobro { get; set; }
        public Nullable<bool> trt { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<bool> manual { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual curso_lectivo curso_lectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recibo_line> recibo_line { get; set; }
        public virtual serie_recibo serie_recibo { get; set; }
    }
}
