//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class recibo_line
    {
        public int idrecibo_line { get; set; }
        public Nullable<int> id_cabecera { get; set; }
        public Nullable<int> num_linea { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> importe_tasas { get; set; }
        public Nullable<decimal> importe_total { get; set; }
        public Nullable<int> idTipoProducto { get; set; }
    
        public virtual recibo_head recibo_head { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
    }
}
