//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemillaAngularWebApi.API.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.audit = new HashSet<audit>();
            this.mail_message = new HashSet<mail_message>();
            this.mail_message_users = new HashSet<mail_message_users>();
            this.refreshtoken = new HashSet<refreshtoken>();
        }
    
        public int idusuarios { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> rol { get; set; }
        public string apiKey { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public Nullable<bool> is_login { get; set; }
    
        public virtual alumno alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<audit> audit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail_message> mail_message { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail_message_users> mail_message_users { get; set; }
        public virtual profesores profesores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<refreshtoken> refreshtoken { get; set; }
    }
}
